version: '3.8'

services:
  db:
    image: postgres
    container_name: postgres_anime_container
    environment:
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_ROOT_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_DATABASE}
    ports:
      - "${POSTGRES_DB_LOCAL_PORT}:${POSTGRES_DB_DOCKER_PORT}"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
