server:
  error:
    include-stacktrace: on_param # Esconde o stack trace de errors apresentados no front-end

spring:
  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_DB_LOCAL_PORT}/${POSTGRES_DB_DATABASE}
    username: ${POSTGRES_DB_USER}
    password: ${POSTGRES_DB_ROOT_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# CUIDADO AO DEFINIR O DIALEC DO HIBERNATE QUANDO ESTIVER USANDO O H2 COM DATABASE PARA OS TESTE
# ELE IR´´A ACUSAR ERRO DE SINTAXE, POIS DEFINIMOS A DO POSTGRESQL, MAS ESTAMOS USANDO A DELE NOS TEST.
# ALTERNATIVA CREIO EU SERIA CRIAR OUTRO application e profile de test.
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: info
    org:
      hibernate:
        SQL: debug   # Define o nível de log para consultas SQL como DEBUG
        type: trace  # Define o nível de log para mensagens de tipo como TRACE