server:
  error:
    include-stacktrace: on_param # Esconde o stack trace de errors apresentados no front-end

spring:
  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_DB_LOCAL_PORT}/${POSTGRES_DB_DATABASE}
    username: ${POSTGRES_DB_USER}
    password: ${POSTGRES_DB_ROOT_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# CUIDADO AO DEFINIR O DIALEC DO HIBERNATE QUANDO ESTIVER USANDO O H2 COM DATABASE PARA OS TESTE
# ELE IR´´A ACUSAR ERRO DE SINTAXE, POIS DEFINIMOS A DO POSTGRESQL, MAS ESTAMOS USANDO A DELE NOS TEST.
# ALTERNATIVA CREIO EU SERIA CRIAR OUTRO application e profile de test.
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: info
    org:
      hibernate:
        SQL: debug   # Define o nível de log para consultas SQL como DEBUG
        type: trace  # Define o nível de log para mensagens de tipo como TRACE


#HABILITANDO ENDPOINTS DE METRICAS DO SPRING ACTUATOR
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus
      # include: "*" -> Habilitando todos os endpoints disponiveis

# INFORMAÇÕES SOBRE A APLICAÇÃO
info:
  app: Spring Boot Essentials [UPDATE] - DevDojo Tutorial
  creator: William Suane
  creator-linkedin: https://www.linkedin.com/in/williamsuane/
  course-channel: https://www.youtube.com/playlist?list=PL62G310vn6nFBIxp6ZwGnm8xMcGE3VA5H
  source-code: https://github.com/devdojobr/springboot2-essentials
  version: 1.0.0
  author: Uanderson Ferreira de Oliveira
  author-github: https://github.com/uandersonFerreira
  author-linkedin: https://www.linkedin.com/in/uandersonferreira/
